title = "Ajith N N"
baseURL = "https://ajithnn.com/"
languageCode = "en-us"
theme = "ananke"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 10 # this is set low for demonstrating with dummy content. Set to a higher number

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  description = "about me."
  twitter = "https://twitter.com/slashring"
  github = "https://github.com/ajithnn"
  gitlab = "https://gitlab.com/ajithnn"
  linkedin = "https://www.linkedin.com/in/ajith-nn-330710a0"
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/ajith_new.jpg"
  recent_posts_number = 2
